name = "katelyatv"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "katelyatv-db"
database_id = "ebf76f9f-0bc4-4cc4-894a-4ca408652157"  # 替换为步骤1中获得的ID

[build]
command = "pnpm install --frozen-lockfile && pnpm run pages:build"

[[build.environment_variables]]
NEXT_PUBLIC_STORAGE_TYPE = "d1"

[vars]
USERNAME = "zhanjun520"
PASSWORD = "3229000.zxc"
NEXT_PUBLIC_ENABLE_REGISTER = "true"
